export const PRODUCT_LIST = 'PRODUCT_LIST';
export const CATEGORY_LIST_FIRST = 'CATEGORY_LIST_FIRST';
export const CATEGORY_LIST_SECOND = 'CATEGORY_LIST_SECOND';
export const CATEGORY_LIST_THIRD = 'CATEGORY_LIST_THIRD';
export const VENDOR_LIST = 'VENDOR_LIST';
export const SUPPLIER_CONTRACT_LIST = 'SUPPLIER_CONTRACT_LIST';
export const PURCHASEORDERLIST = 'PURCHASEORDERLIST';
