export const PRODUCT_LIST = 'PRODUCT_LIST';
export const CATEGORY_LIST_FIRST = 'CATEGORY_LIST_FIRST';
export const CATEGORY_LIST_SECOND = 'CATEGORY_LIST_SECOND';
export const CATEGORY_LIST_THIRD = 'CATEGORY_LIST_THIRD';
export const VENDOR_LIST = 'VENDOR_LIST';
export const SUPPLIER_CONTRACT_LIST = 'SUPPLIER_CONTRACT_LIST';
export const PURCHASEORDERLIST = 'PURCHASEORDERLIST';
export const PURCHASEORDERDETAIL = 'PURCHASEORDERDETAIL';
export const SUPPERLIERLIST = 'SUPPERLIERLIST';
export const PUCHASECATEGORYLIST = 'PUCHASECATEGORYLIST';
export const PURSELECTPROLIST = 'PURSELECTPROLIST';
export const ADDPURWAREHOUSE = 'ADDPURWAREHOUSE';
export const ADDPURCHASEORDER = 'ADDPURCHASEORDER';
export const USER_LIST = 'USER_LIST';
export const DEPT_LIST = 'DEPT_LIST';
export const MENU_LIST = 'MENU_LIST';
export const ROLE_LIST = 'ROLE_LIST';
export const USER_NAV = 'USER_NAV';
export const PURCHASEORDERDETAILTABA = 'PURCHASEORDERDETAILTABA';
export const PRODUCT_FEATURE_LIST = 'PRODUCT_FEATURE_LIST';
export const SUPPLIER_PRICE = 'SUPPLIER_PRICE';
export const STORAGELIST = 'STORAGELIST';
export const FUN_TREE = 'FUN_TREE';
export const FUN_LIST = 'FUN_LIST';


